"""rename department

Revision ID: fe12cd34439f
Revises: 83fc76ab7f55
Create Date: 2025-02-26 11:11:58.358962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe12cd34439f'
down_revision = '83fc76ab7f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department','departments')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments','department')
    # ### end Alembic commands ###
